### ISSUE TITLE
TypeLoadException on load

### ISSUE THREAD

**Issue by jtenos** [ralmsdeveloper/Ralms.EntityFrameworkCore.Extensions#7]
Running in .NET Core 3.1. I see this project hasn't been updated in a couple years, so is it not compatible with .NET Core 3.1?

```
Unhandled exception. System.TypeLoadException: Method 'get_Info' in type 'Ralms.EntityFrameworkCore.Extensions.RalmsExOptionsExtension' from assembly 'Ralms.EntityFrameworkCore.Extensions, Version=1.0.5.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at Microsoft.EntityFrameworkCore.RalmsDbContextOptionsBuilderExtensions.RalmsExtendFunctions(DbContextOptionsBuilder optionsBuilder)
   at MyContext.OnConfiguring(DbContextOptionsBuilder optionsBuilder) in    at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_Model()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityType()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.CheckState()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.get_EntityQueryable()
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

**Comment by ralmsdeveloper** [comment]
Hello @jtenos, I will be updating this week, there are many things I intend to add, but by the end of this week I will update this project, I have been very busy with things from the company.

**Comment by jtenos** [comment]
Awesome, looking forward to it.

**Comment by jtenos** [comment]
Looks like this project is abandoned, closing this issue since it's 6 versions behind anyway.
